name: Deploy to VPS

on:
  push:
    branches: [ feature/new_latest_migration_mysql ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH commands: git pull, build, restart
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 66.116.198.204
        username: deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/beyoushop
          git reset --hard
          git pull origin main
          npm ci
          npm run build
          pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
